apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: devops1
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: nmsrinivas/dockerjenkins
      ports:
        - containerPort: 3000
      volumes:
      -name: docker-sock
      hostPath: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  namespace: devops1
  name: jenkinsservice
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30001
    protocol: TCP
