apiVersion: apps/v1betav1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: anish0210/jenkins
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:  
  name: jenkinsService
spec:
  selector:    
    app: jenkins
  type: NodePort
  ports:  
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30001
    protocol: TCP
