apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: devops1
  name: spring-boot-app
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: anish0210/springboot
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: devops1
  name: spring-boot-app-service
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30051
    protocol: TCP
