apiVersion: v1
kind: Service
metadata:  
  name: myapp
spec:
  selector:    
    app: myapp
  type: NodePort
  ports:  
  - name: http
    port: 3000
    targetPort: 80
    nodePort: 30036
    protocol: TCP
