apiVersion: apps/v1betav1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: anish0210/springboot
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:  
  name: myapp
spec:
  selector:    
    app: myapp
  type: NodePort
  ports:  
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30036
    protocol: TCP
